main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.index, name = "index"),
    path('blog/', views.blog, name = "blog"),
    path('blog/post/<int:post_id>', views.post, name = "post"),
    path('contact/', views.contact, name = "contact"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=300)
    content = RichTextField()
    posted_date = models.DateTimeField(auto_now_add=True)

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()

class WorkExperience(models.Model):
    title = models.CharField(max_length=250)
    workplace = models.CharField(max_length=200)
    description = models.TextField()
    starting_date = models.DateField()
    ending_date = models.DateField()

class Certificate(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    issue_date = models.DateField()
    url = models.URLField()

class Project(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    starting_date = models.DateField()
    ending_date = models.DateField()
    url = models.URLField(blank=True)
    


    

main/forms.py
from django import forms
from main.models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
# from django.http import HttpResponse
from django.core.paginator import Paginator
from main.models import Post
from main.models import Contact, WorkExperience, Certificate, Project
from main.forms import ContactForm

# from django.core.email import EmailMessage
# from django.conf import settings as conf_settings

from django.contrib import messages


# Create your views here.
def index(request):
    work_experience = WorkExperience.objects.all()
    project = Project.objects.all()
    certificate = Certificate.objects.all()

    context = {'work_experience':work_experience, 'project':project, 'certificate':certificate}
    return render(request, 'main/index.html', context)

def blog(request):
    posts = Post.objects.all().order_by('-posted_date')
    paginator = Paginator(posts, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj}
    return render(request, 'main/blog.html', context)

def post(request, post_id=None):
    post = get_object_or_404(Post, id=post_id)
    context = {'post':post}
    return render(request, 'main/post.html', context)

def contact(request):
    form = ContactForm(request.POST or None)

    if form.is_valid():

        # instance = form.save(commit=False)
        # name = instance.name
        # email = instance.email
        # message = instance.message

        # EmailMessage(
        #     'New message from %s', %name,
        #     'Hi admin, This is my message from this email address: %s\n\n Message: %s', %(email, message),
        #     conf_settings.EMAIL_HOST_USER,
        #     ['tejashvigoyal2910@gmail.com'],
        # ).send()

        form.save()

        messages.success(request, 'Your message has been sent!')

        return redirect('contact')
    context = {'form':form}
    return render(request, 'main/contact.html', context)

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>

    <!-- Style section -->
    {% block style %}{% endblock %}

    <!-- JavaScript section -->
    {% block script %}{% endblock %}
  </head>
  <body>
      <!-- content section -->
      {% block content %}{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

main/templates/main/blog.html
{% extends 'main/index.html' %}
{% block title %}Mysite | Blog{% endblock %}

{% block main-content %}

{% for post in page_obj %}
<h1><a href="{% url 'post' post.id %}">{{post.title}}</a></h1>
<!-- <p>{{post.content | safe}}</p> -->
<p>{{post.posted_date|date:"F d, Y"}}</p>
{% endfor %}

<div class="row mt-4 mb-n2">
    <div class="col-12 text-center text-muted">
        <p><span>Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></p>
    </div>
</div>

<ul class="pagination pagination-sm justify-content-center">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
    {% endif %}
</ul>


{% endblock %}

main/templates/main/contact.html
{% extends 'main/index.html' %}
{% load crispy_forms_tags %}

{% block title %}Mysite | Contact{% endblock %}

{% block main-content %}

{% if messages %}
    {% for message in messages %}
        <div class="container-fluid alert alert-{{ message.tags }}">
            <div class="container message">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <span id="id_message">{{ message }}</span>
            </div>
        </div>
    {% endfor %}
{% endif %}

<div class="container text-center mt-5 mb-5">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>

{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %}Mysite | Home{% endblock %}

{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Yash Goyal</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item ">
                <a class="nav-link" href="{% url 'blog' %}">Blog</a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Contact</a>
            </li>
            
            <!-- <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> -->
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        <div class="mx-2">
            <button class="btn btn-danger" data-toggle="modal" data-target="#loginModal">Login</button>
            <button class="btn btn-danger" data-toggle="modal" data-target="#signupModal">SignUp</button>
        </div>
    </div>
</nav>

{% block main-content %}

<!-- <h1>Hello World I am Nobody</h1>

{% for post in posts %}
<h1> {{post.title}} </h1>
<p> {{post.content|safe}} </p>
{% endfor %} -->



<div class="container mt-5">
    <h1 class="text-center">Work Experience</h1>
    {% for work in work_experience %}
    <div>
        <h2>{{work.title}}</h2>
        <p><small>{{work.description}}</small></p>
        <p><small>Starting date: {{work.starting_date}}| Ending date: {{work.ending_date}}</small></p>
    </div><hr>
    {% endfor %}
</div>
<div class="container mt-5">
    <h1 class="text-center">Certificates</h1>
    {% for cert in certificate %}
    <div>
        <h2>{{cert.title}}</h2>
        <p><small>Url: <a href="{{cert.url}}">{{cert.url}}</a></small></p>
        <p><small>{{cert.description}}</small></p>
        <p><small>Issued date: {{cert.issue_date}}</small></p>
    </div><hr>
    {% endfor %}
</div>
<div class="container mt-5">
    <h1 class="text-center">Projects</h1>
    {% for proj in project %}
    <div>
        <h2>{{proj.title}}</h2>
        {% if proj.url %}
        <p><small>Url: <a href="{{proj.url}}">{{proj.url}}</a></small></p>
        {% endif %}
        <p><small>{{proj.description}}</small></p>
        <p><small>Starting date: {{proj.starting_date}}| Ending date: {{proj.ending_date}}</small></p>
    </div><hr>
    {% endfor %}
</div>
{% endblock %}

{% endblock %}

main/templates/main/post.html
{% extends 'main/index.html' %}
{% block title %}Mysite | {{post.title}}{% endblock %}

{% block main-content %}
<h1>{{post.title}}</h1>
<p>{{post.content|safe}}</p>
<p>{{post.posted_date|date:"F d, Y"}}</p>


{% endblock %}